In [10]:
import pandas as pd
import numpy as np
import seaborn as sns 
import math as m

In [11]:
datos= pd.read_csv('EXAMEN TE.csv')

In [12]:
datos

,"Resultado de la clasificación no supervisada realizada en la superficie de trigo, en el ciclo de siembra otoño-invierno 1995-1996. Río Mayo, Sonora, México.",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,CLUSTER,CANTIDAD DE PIXELES,VALOR ESPECTRAL MEDIO,NaN,NaN
1,NaN,NaN,TM2,TM3,TM4
2,1,254745,23.11,28.59,33.75
3,2,329174,21.59,23.58,43.6
4,3,280238,27.35,34.58,48.53
5,4,561113,20.93,21.18,53.75
6,5,748527,19.23,17.52,62.21
7,6,831918,17.98,14.92,70.4
8,7,691350,17.81,14.15,78.53
9,8,466315,17.66,13.52,86.26
10,9,218683,17.97,13.56,93.9
11,10,69071,18.55,13.88,102.39
12,11,206,45.85,66.67,76.29
13,12,0,42,58,123
14,"TM2= reflectancia en el verde, 500-590 nm, TM3...",NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN
16,Sensor Remoto utilizado Landsat TM y electroma...,NaN,NaN,NaN,NaN
17,"z = 1.96, 1.64 y 1.28 para niveles de confianz...",NaN,NaN,NaN,NaN

In [ ]:
md= datos[['Unnamed: 3']]
md